In [ ]:
#%pip install pillow pytesseract

In [1]:
import re
import json
import uuid
import math
import random
from pathlib import Path
from typing import List, Dict, Optional

import fitz  # PyMuPDF
import numpy as np
import pandas as pd
from io import BytesIO
from typing import Optional

import fitz  # PyMuPDF
from PIL import Image
import pytesseract

from sklearn.metrics.pairwise import cosine_similarity

# Embedding model
from sentence_transformers import SentenceTransformer

/home/yash/Dev_Projects/.venv_notebook/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
#from pathlib import Path

BASE_DIR = Path("/home/yash/Dev_Projects")
NOTEBOOK_RECORDS_DIR = BASE_DIR / "notebook_records"
NOTEBOOK_RECORDS_DIR.mkdir(parents=True, exist_ok=True)

print("Notebook records dir:", NOTEBOOK_RECORDS_DIR)

Notebook records dir: /home/yash/Dev_Projects/notebook_records

In [3]:
# =========================
# INPUT PDF
# =========================
PDF_PATH = Path("/home/yash/Dev_Projects/RAG PDF/project/Reports/Annual-Report-2024-25.pdf")

assert PDF_PATH.exists(), f"PDF not found: {PDF_PATH}"

# =========================
# CONFIG
# =========================
TARGET_CHUNK_WORDS = 180
MAX_CHUNK_WORDS = 260
MIN_CHUNK_WORDS = 80
CHUNK_OVERLAP_WORDS = 30

MAX_HEADING_WORDS = 12
MIN_HEADING_UPPER_RATIO = 0.60

TOP_K = 5

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

random.seed(42)
np.random.seed(42)

In [4]:
# ==========================================
# PHASE 1 — PDF INGESTION + PARSING
# ==========================================

def normalize_spaces(text: str) -> str:
    text = text.replace("\xa0", " ")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def clean_candidate_line(line: str) -> str:
    line = normalize_spaces(line)
    line = re.sub(r"^[^\w]+|[^\w\)\.&,\- ]+$", "", line).strip()
    return line


def extract_report_title(pages: list[dict]) -> Optional[str]:
    first_pages = pages[:5]
    title_candidates = []

    for page in first_pages:
        lines = [clean_candidate_line(x) for x in page["text"].splitlines() if x.strip()]
        for line in lines[:40]:
            line_l = line.lower()
            if "annual report" in line_l or "integrated report" in line_l:
                title_candidates.append(line)

    if title_candidates:
        title_candidates = sorted(title_candidates, key=len)
        return title_candidates[0]

    return None


def extract_financial_year(document_name: str, pages: list[dict]) -> Optional[str]:
    candidates = []

    candidates.extend(re.findall(r"FY[-_ ]?(20\d{2}[-/]\d{2,4})", document_name, flags=re.I))
    candidates.extend(re.findall(r"(20\d{2}[-/]\d{2,4})", document_name, flags=re.I))

    first_pages_text = "\n".join([p["text"] for p in pages[:8]])
    candidates.extend(re.findall(r"FY[- ]?(20\d{2}[-/]\d{2,4})", first_pages_text, flags=re.I))
    candidates.extend(re.findall(r"(20\d{2}[-/]\d{2,4})", first_pages_text, flags=re.I))

    if not candidates:
        return None

    normalized = []
    for c in candidates:
        c = c.upper().replace("FY", "").strip()
        c = re.sub(r"\s+", "", c)
        normalized.append(c)

    normalized.sort(key=lambda x: (0 if re.fullmatch(r"20\d{2}[-/]\d{2}", x) else 1, len(x)))
    return normalized[0]


def render_page_for_ocr(pdf, page_index: int, zoom: float = 3.0) -> Image.Image:
    page = pdf[page_index]
    matrix = fitz.Matrix(zoom, zoom)
    pix = page.get_pixmap(matrix=matrix, alpha=False)
    img = Image.open(BytesIO(pix.tobytes("png")))
    return img


def ocr_page_image(image: Image.Image) -> str:
    text = pytesseract.image_to_string(image, lang="eng")
    return normalize_spaces(text)


def extract_last_page_ocr_text(pdf) -> str:
    """
    OCR the last page first.
    If OCR result is too weak, try the previous 2 pages as fallback.
    """
    total_pages = len(pdf)
    candidate_indices = [total_pages - 1, total_pages - 2, total_pages - 3]

    for idx in candidate_indices:
        if idx < 0:
            continue

        img = render_page_for_ocr(pdf, idx, zoom=3.0)
        text = ocr_page_image(img)

        if len(text.strip()) >= 30:
            return text

    return ""


def is_bad_company_candidate(line: str) -> bool:
    line_l = line.lower().strip()

    bad_exact = {
        "contents",
        "content",
        "index",
        "notice",
        "corporate governance",
        "financial statements",
        "standalone financial statements",
        "consolidated financial statements",
        "management discussion and analysis report",
        "business responsibility and sustainability report",
        "forward-looking statement",
        "working capital loan",
        "financial liabilities",
        "financial assets",
        "bankers",
        "auditors",
        "registrars",
        "investors",
        "annual report",
        "integrated report",
        "director, finance",
        "director finance",
    }

    bad_contains = {
        "annual report",
        "integrated report",
        "contents",
        "content",
        "index",
        "corporate governance",
        "financial statements",
        "standalone financial statements",
        "consolidated financial statements",
        "management discussion",
        "sustainability report",
        "working capital loan",
        "liabilities",
        "liability",
        "assets",
        "asset",
        "equity",
        "borrowings",
        "receivables",
        "payables",
        "cash flow",
        "cash flows",
        "profit and loss",
        "balance sheet",
        "statement of",
        "notes annexed",
        "notes to",
        "director, finance",
        "director finance",
        "chairman",
        "managing director",
        "company secretary",
    }

    if line_l in bad_exact:
        return True

    if any(x in line_l for x in bad_contains):
        return True

    if len(line.split()) < 2:
        return True

    if len(line.split()) > 10:
        return True

    if len(line) > 120:
        return True

    if re.search(r"\b\d{2,}\b", line_l):
        return True

    return False


def score_company_candidate(line: str) -> int:
    score = 0
    line_l = line.lower()

    suffix_words = [
        "limited", "ltd", "bank", "finance", "financial services",
        "capital", "services", "industries", "motors", "technology",
        "technologies", "corporation", "corp", "holdings",
        "company", "enterprises"
    ]

    strong_patterns = [
        r"\blimited\b",
        r"\bltd\b",
        r"\bbank\b",
        r"\bfinance\b",
        r"\bfinancial services\b",
        r"\bcapital\b",
        r"\bservices\b",
        r"\bindustries\b",
        r"\bmotors\b",
        r"\btechnologies\b",
        r"\bcorporation\b",
        r"\bholdings\b",
    ]

    if 2 <= len(line.split()) <= 7:
        score += 2

    if line.istitle():
        score += 2

    if re.fullmatch(r"[A-Za-z0-9&,\.\-() ]+", line):
        score += 1

    if any(word in line_l for word in suffix_words):
        score += 8

    if any(re.search(p, line_l) for p in strong_patterns):
        score += 8

    # Strong preference for realistic company names
    if 2 <= len(line.split()) <= 5:
        score += 2

    return score


def extract_company_name_from_last_page_ocr(ocr_text: str) -> Optional[str]:
    """
    Primary strategy:
    extract company name from OCR text of last page / back pages.
    """
    lines = [clean_candidate_line(x) for x in ocr_text.splitlines() if x.strip()]

    candidates = []
    for line in lines[:80]:
        if is_bad_company_candidate(line):
            continue

        score = score_company_candidate(line)
        if score > 0:
            candidates.append((score, line))

    if not candidates:
        return None

    candidates.sort(key=lambda x: (-x[0], len(x[1])))

    preferred = [
        item for item in candidates
        if any(x in item[1].lower() for x in [
            "limited", "ltd", "bank", "finance", "industries",
            "motors", "corporation", "holdings", "services", "capital"
        ])
    ]

    if preferred:
        return preferred[0][1]

    return candidates[0][1]


# -------- Parse PDF --------
pdf = fitz.open(PDF_PATH)

pages = []
empty_pages = 0

for i in range(len(pdf)):
    page = pdf[i]
    text = page.get_text("text") or ""
    text = text.strip()

    if not text:
        empty_pages += 1

    pages.append({
        "page_number": i + 1,
        "text": text
    })

document_id = uuid.uuid4().hex
document_name = PDF_PATH.name

# -------- OCR from last page / back pages --------
last_page_ocr_text = extract_last_page_ocr_text(pdf)

print("=" * 100)
print("LAST PAGE OCR PREVIEW")
print("=" * 100)
print(last_page_ocr_text[:3000])

company_name = extract_company_name_from_last_page_ocr(last_page_ocr_text)
financial_year = extract_financial_year(document_name, pages)
report_title = extract_report_title(pages)

phase1_output = {
    "document_id": document_id,
    "document_name": document_name,
    "company_name": company_name,
    "financial_year": financial_year,
    "report_title": report_title,
    "total_pages": len(pages),
    "empty_pages": empty_pages,
    "pages": pages,
    "last_page_ocr_text": last_page_ocr_text
}

print("=" * 100)
print("PHASE 1 COMPLETE")
print("=" * 100)
print("Document Name  :", phase1_output["document_name"])
print("Document ID    :", phase1_output["document_id"])
print("Company Name   :", phase1_output["company_name"])
print("Financial Year :", phase1_output["financial_year"])
print("Report Title   :", phase1_output["report_title"])
print("Total Pages    :", phase1_output["total_pages"])
print("Empty Pages    :", phase1_output["empty_pages"])

phase1_save_path = NOTEBOOK_RECORDS_DIR / "phase1_output.json"

with open(phase1_save_path, "w", encoding="utf-8") as f:
    json.dump(phase1_output, f, ensure_ascii=False, indent=2)

print("\nPhase 1 output saved to:", phase1_save_path)

====================================================================================================
LAST PAGE OCR PREVIEW
====================================================================================================
(0 Inunrk
HMT Limited

CIN No. L29230KA1953G01000748
HMT Bhavan, No. 59,
Bellary Road, Bengaluru - 560 032
Website : www.hmtindia.com
====================================================================================================
PHASE 1 COMPLETE
====================================================================================================
Document Name  : Annual-Report-2024-25.pdf
Document ID    : cac28f9d866d468b9b958ee01d9366e6
Company Name   : HMT Limited
Financial Year : 2024-25
Report Title   : Annual Report 2024 - 25
Total Pages    : 241
Empty Pages    : 3

Phase 1 output saved to: /home/yash/Dev_Projects/notebook_records/phase1_output.json

In [5]:
# ==========================================
# PHASE 2 — CLEANING + SECTIONING + CHUNKING
# ==========================================

def clean_line(line: str) -> str:
    line = line.strip()
    line = re.sub(r"\s+", " ", line)
    return line


def remove_page_artifacts(text: str) -> str:
    cleaned_lines = []

    for raw_line in text.splitlines():
        line = clean_line(raw_line)

        if not line:
            cleaned_lines.append("")
            continue

        if re.fullmatch(r"\d{1,4}", line):
            continue

        if re.fullmatch(r"page\s+\d{1,4}", line, flags=re.I):
            continue

        if re.fullmatch(r"[\*\-–—•\s]{3,}", line):
            continue

        if line.lower().strip() in {
            "annual report",
            "annual report 2024-25",
            "integrated report"
        }:
            continue

        cleaned_lines.append(line)

    return "\n".join(cleaned_lines).strip()


def join_broken_lines(text: str) -> str:
    lines = text.splitlines()
    merged = []
    buffer = []

    def flush_buffer():
        nonlocal buffer, merged
        if buffer:
            merged.append(" ".join(buffer).strip())
            buffer = []

    for line in lines:
        stripped = line.strip()

        if not stripped:
            flush_buffer()
            merged.append("")
            continue

        if len(stripped.split()) <= MAX_HEADING_WORDS and stripped.isupper():
            flush_buffer()
            merged.append(stripped)
            continue

        if re.match(r"^(\-|\•|\*|\d+\.)\s+", stripped):
            flush_buffer()
            merged.append(stripped)
            continue

        buffer.append(stripped)

    flush_buffer()
    text = "\n".join(merged)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def clean_page_text(text: str) -> str:
    text = normalize_spaces(text)
    text = remove_page_artifacts(text)
    text = join_broken_lines(text)
    text = normalize_spaces(text)
    return text


def clean_page_text_for_contents(text: str) -> str:
    text = normalize_spaces(text)
    text = remove_page_artifacts(text)
    return text


# -------- Clean all pages --------
cleaned_pages = []
for p in phase1_output["pages"]:
    cleaned_pages.append({
        "page_number": p["page_number"],
        "text": clean_page_text(p["text"])
    })

# Separate version for contents/index parsing: no line-joining
contents_pages = []
for p in phase1_output["pages"]:
    contents_pages.append({
        "page_number": p["page_number"],
        "text": clean_page_text_for_contents(p["text"])
    })


# -------- Helper Functions for Contents / Index page detection --------
def normalize_for_match(text: str) -> str:
    return re.sub(r"\s+", " ", text.lower()).strip()


# def score_contents_page(text: str) -> int:
#     text_l = normalize_for_match(text)
#     score = 0

#     if re.search(r"\bcontents\b", text_l):
#         score += 8
#     if re.search(r"\bcontent\b", text_l):
#         score += 5
#     if re.search(r"\bindex\b", text_l):
#         score += 6

#     lines = [line.strip() for line in text.splitlines() if line.strip()]

#     dotted_lines = 0
#     numbered_lines = 0

#     for line in lines:
#         if re.search(r"\.{3,}", line):
#             dotted_lines += 1
#         if re.search(r"\b\d{1,3}\s*$", line):
#             numbered_lines += 1

#     score += min(dotted_lines, 15)
#     score += min(numbered_lines, 15)

#     return score

def score_contents_page(text: str) -> int:
    text_l = normalize_for_match(text)
    score = 0

    has_keyword = False

    if re.search(r"\bcontents\b", text_l):
        score += 10
        has_keyword = True
    if re.search(r"\bcontent\b", text_l):
        score += 6
        has_keyword = True
    if re.search(r"\bindex\b", text_l):
        score += 8
        has_keyword = True

    if not has_keyword:
        return 0

    lines = [line.strip() for line in text.splitlines() if line.strip()]
    dotted_lines = sum(1 for line in lines if re.search(r"\.{3,}", line))
    numbered_lines = sum(1 for line in lines if re.search(r"\b\d{1,3}\s*$", line))

    score += min(dotted_lines, 15)
    score += min(numbered_lines, 15)

    return score


def find_contents_pages(pages: List[Dict], max_scan_pages: int = 20) -> List[int]:
    candidate_scores = []

    for page in pages[:max_scan_pages]:
        page_num = page["page_number"]
        text = page["text"]
        score = score_contents_page(text)

        if score >= 8:
            candidate_scores.append((page_num, score))

    if not candidate_scores:
        return []

    candidate_scores = sorted(candidate_scores, key=lambda x: x[0])

    selected_pages = [candidate_scores[0][0]]
    for page_num, score in candidate_scores[1:]:
        if page_num - selected_pages[-1] <= 2:
            selected_pages.append(page_num)

    return selected_pages


def clean_contents_entry_title(title: str) -> str:
    title = normalize_spaces(title)
    title = re.sub(r"\.{2,}", " ", title)
    title = re.sub(r"\s{2,}", " ", title).strip(" .-–—")
    return title.strip()


def is_valid_contents_title(title: str) -> bool:
    title_l = title.lower().strip()

    if not title or len(title.split()) < 2:
        return False

    bad_titles = {
        "contents",
        "content",
        "index",
        "annual report",
        "annual report 2024-25",
    }

    if title_l in bad_titles:
        return False

    if re.fullmatch(r"[\d\.\-\(\) ]+", title):
        return False

    return True


def is_major_section_title(title: str) -> bool:
    title_l = title.lower().strip()

    major_patterns = [
        r"historical perspective",
        r"board of directors",
        r"performance highlights",
        r"chairman.?s address",
        r"chairman.?s message",
        r"directors.? report",
        r"notice",
        r"csr",
        r"corporate social responsibility",
        r"annual report on csr activities",
        r"management discussion",
        r"management discussions",
        r"management discussion and analysis",
        r"management discussions and analysis",
        r"report on corporate governance",
        r"certificate on corporate governance",
        r"corporate governance",
        r"secretarial audit report",
        r"ceo\s*&\s*cfo certificate",
        r"ceo\s+and\s+cfo certificate",
        r"independent auditor.?s report",
        r"comments of c\s*&\s*ag",
        r"comments of c and ag",
        r"significant accounting policies",
        r"notes forming part of standalone financial statement",
        r"notes forming part of standalone financial statements",
        r"notes forming part of consolidated financial statement",
        r"notes forming part of consolidated financial statements",
        r"standalone financial statement",
        r"standalone financial statements",
        r"consolidated financial statement",
        r"consolidated financial statements",
        r"business responsibility",
        r"sustainability",
        r"brsr",
    ]

    return any(re.search(pattern, title_l) for pattern in major_patterns)


def parse_contents_entries_from_page(text: str) -> List[Dict]:
    entries = []
    lines = [line.strip() for line in text.splitlines() if line.strip()]

    extracted = []

    for line in lines:
        # Case 1: title ...... page_number
        matches = re.findall(r"([A-Za-z][A-Za-z0-9’'&,/\-\(\) ]+?)\s*\.{2,}\s*(\d{1,3})", line)
        for title, page_no in matches:
            extracted.append((clean_contents_entry_title(title), int(page_no)))

        # Case 2: title + multiple spaces + page_number
        matches = re.findall(r"([A-Za-z][A-Za-z0-9’'&,/\-\(\) ]+?)\s{2,}(\d{1,3})(?=\s|$)", line)
        for title, page_no in matches:
            extracted.append((clean_contents_entry_title(title), int(page_no)))

        # Case 3: merged text like "... Company 5 Notice to Shareholders 6 ..."
        matches = re.findall(r"([A-Z][A-Za-z0-9’'&,/\-\(\) ]+?)\s+(\d{1,3})(?=\s+[A-Z]|\s*$)", line)
        for title, page_no in matches:
            extracted.append((clean_contents_entry_title(title), int(page_no)))

        # Case 4: title with explicit page range
        m = re.match(r"^(.*?)\s*\(Pages?\s+(\d{1,3})\s+to\s+(\d{1,3})\)\s*$", line, flags=re.I)
        if m:
            extracted.append((clean_contents_entry_title(m.group(1)), int(m.group(2))))

    seen = set()
    for title, start_page in extracted:
        if not is_valid_contents_title(title):
            continue

        key = (title.lower(), start_page)
        if key in seen:
            continue
        seen.add(key)

        entries.append({
            "title": title,
            "start_page": start_page
        })

    return entries


def parse_contents_entries(pages: List[Dict], contents_page_numbers: List[int]) -> List[Dict]:
    all_entries = []
    page_lookup = {p["page_number"]: p for p in pages}

    for page_num in contents_page_numbers:
        page = page_lookup.get(page_num)
        if not page:
            continue

        page_entries = parse_contents_entries_from_page(page["text"])
        all_entries.extend(page_entries)

    seen = set()
    deduped = []
    for entry in all_entries:
        key = (entry["title"].lower(), entry["start_page"])
        if key not in seen:
            seen.add(key)
            deduped.append(entry)

    deduped = sorted(deduped, key=lambda x: x["start_page"])
    return deduped


def classify_section_type(title: str) -> str:
    title_l = title.lower().strip()

    patterns = [
        (r"historical perspective", "general"),
        (r"board of directors", "leadership"),
        (r"performance highlights", "highlights"),
        (r"chairman.?s address", "leadership_message"),
        (r"chairman.?s message", "leadership_message"),
        (r"directors.? report", "board_report"),
        (r"notice", "notice"),
        (r"csr", "esg"),
        (r"corporate social responsibility", "esg"),
        (r"annual report on csr activities", "esg"),
        (r"management discussion", "management_discussion"),
        (r"management discussions", "management_discussion"),
        (r"report on corporate governance", "governance"),
        (r"certificate on corporate governance", "governance"),
        (r"corporate governance", "governance"),
        (r"secretarial audit report", "audit_report"),
        (r"ceo\s*&\s*cfo certificate", "compliance_certificate"),
        (r"ceo\s+and\s+cfo certificate", "compliance_certificate"),
        (r"independent auditor.?s report", "audit_report"),
        (r"comments of c\s*&\s*ag", "audit_report"),
        (r"comments of c and ag", "audit_report"),
        (r"significant accounting policies", "financial_statements"),
        (r"notes forming part of standalone financial statement", "financial_statements"),
        (r"notes forming part of standalone financial statements", "financial_statements"),
        (r"notes forming part of consolidated financial statement", "financial_statements"),
        (r"notes forming part of consolidated financial statements", "financial_statements"),
        (r"standalone financial statement", "financial_statements"),
        (r"standalone financial statements", "financial_statements"),
        (r"consolidated financial statement", "financial_statements"),
        (r"consolidated financial statements", "financial_statements"),
        (r"business responsibility", "esg"),
        (r"sustainability", "esg"),
        (r"brsr", "esg"),
    ]

    for pattern, section_type in patterns:
        if re.search(pattern, title_l):
            return section_type

    return "general"


def build_sections_from_contents(cleaned_pages: List[Dict], contents_entries: List[Dict]) -> List[Dict]:
    if not contents_entries:
        return []

    total_pages = cleaned_pages[-1]["page_number"] if cleaned_pages else 0
    page_lookup = {p["page_number"]: p["text"] for p in cleaned_pages}

    sections = []

    first_start = contents_entries[0]["start_page"]
    if first_start > 1:
        opening_text_parts = []
        for pnum in range(1, first_start):
            if pnum in page_lookup and page_lookup[pnum].strip():
                opening_text_parts.append(page_lookup[pnum].strip())

        opening_text = "\n\n".join(opening_text_parts).strip()
        if opening_text:
            sections.append({
                "section_id": str(uuid.uuid4()),
                "title": "Document Opening",
                "section_type": "general",
                "page_start": 1,
                "page_end": first_start - 1,
                "text": opening_text
            })

    for idx, entry in enumerate(contents_entries):
        title = entry["title"]
        start_page = entry["start_page"]

        if idx < len(contents_entries) - 1:
            end_page = contents_entries[idx + 1]["start_page"] - 1
        else:
            end_page = total_pages

        if start_page > end_page:
            continue

        text_parts = []
        for pnum in range(start_page, end_page + 1):
            if pnum in page_lookup and page_lookup[pnum].strip():
                text_parts.append(page_lookup[pnum].strip())

        section_text = "\n\n".join(text_parts).strip()
        if not section_text:
            continue

        sections.append({
            "section_id": str(uuid.uuid4()),
            "title": title,
            "section_type": classify_section_type(title),
            "page_start": start_page,
            "page_end": end_page,
            "text": section_text
        })

    return sections


# -------- Detect sections using Contents / Index pages --------
contents_page_numbers = find_contents_pages(contents_pages, max_scan_pages=20)
contents_entries = parse_contents_entries(contents_pages, contents_page_numbers)
contents_entries = [e for e in contents_entries if is_major_section_title(e["title"])]
sections = build_sections_from_contents(cleaned_pages, contents_entries)

print("Detected contents/index pages:", contents_page_numbers)
print("Parsed contents entries:", len(contents_entries))

if contents_page_numbers:
    print("\nRaw contents page preview:\n")
    page_lookup_debug = {p["page_number"]: p for p in contents_pages}
    for pnum in contents_page_numbers:
        print("=" * 100)
        print(f"CONTENTS PAGE {pnum}")
        print("-" * 100)
        print(page_lookup_debug[pnum]["text"][:3000])
        print()

if contents_entries:
    print("Sample parsed entries:")
    for entry in contents_entries[:15]:
        print(f"- {entry['title']} -> {entry['start_page']}")
else:
    print("No contents entries parsed. Falling back to heading-based section detection.")


# -------- Fallback: heading-based section detection --------
if not sections:
    def uppercase_ratio(text: str) -> float:
        letters = [ch for ch in text if ch.isalpha()]
        if not letters:
            return 0.0
        upper = [ch for ch in letters if ch.isupper()]
        return len(upper) / len(letters)

    def looks_like_heading(line: str) -> bool:
        line = line.strip()

        if not line:
            return False

        word_count = len(line.split())

        if word_count < 2 or word_count > 10:
            return False

        if line.endswith(".") or line.endswith(";") or line.endswith(":"):
            return False

        if re.search(r"\d{2,}", line):
            return False

        if line.count(",") > 1:
            return False

        if re.match(r"^(\-|\•|\*|\d+\.)\s+", line):
            return False

        if line.isupper() and 2 <= word_count <= 8:
            return True

        if re.fullmatch(r"[A-Z][A-Za-z&/\-(), ]+", line):
            if uppercase_ratio(line) >= 0.30:
                return True
            if line.istitle():
                return True

        return False

    fallback_sections = []

    current_title = "Document Opening"
    current_type = "general"
    current_page_start = cleaned_pages[0]["page_number"] if cleaned_pages else 1
    current_text_parts = []

    for page in cleaned_pages:
        lines = page["text"].splitlines()
        page_buffer = []

        for line in lines:
            if looks_like_heading(line):
                title_candidate = line.strip()

                if page_buffer:
                    current_text_parts.append("\n".join(page_buffer).strip())
                    page_buffer = []

                existing_text = "\n".join(current_text_parts).strip()
                if existing_text:
                    text = "\n".join(part for part in current_text_parts if part.strip()).strip()
                    if text:
                        fallback_sections.append({
                            "section_id": str(uuid.uuid4()),
                            "title": current_title,
                            "section_type": classify_section_type(current_title),
                            "page_start": current_page_start,
                            "page_end": page["page_number"],
                            "text": text
                        })

                    current_title = title_candidate
                    current_type = classify_section_type(title_candidate)
                    current_page_start = page["page_number"]
                    current_text_parts = []
                else:
                    current_title = title_candidate
                    current_type = classify_section_type(title_candidate)
            else:
                page_buffer.append(line)

        if page_buffer:
            current_text_parts.append("\n".join(page_buffer).strip())

    if cleaned_pages:
        text = "\n".join(part for part in current_text_parts if part.strip()).strip()
        if text:
            fallback_sections.append({
                "section_id": str(uuid.uuid4()),
                "title": current_title,
                "section_type": current_type,
                "page_start": current_page_start,
                "page_end": cleaned_pages[-1]["page_number"],
                "text": text
            })

    sections = fallback_sections


# -------- Validate sections --------
validated_sections = []
for s in sections:
    if not s["title"].strip():
        continue
    if not s["text"].strip():
        continue
    if s["page_start"] > s["page_end"]:
        continue
    validated_sections.append(s)

sections = validated_sections

print("\nFinal sections after validation:", len(sections))
for s in sections[:15]:
    print(f"{s['page_start']:>3}-{s['page_end']:<3} | {s['section_type']:<22} | {s['title']}")


# -------- Chunking --------
def split_into_paragraphs(text: str) -> List[str]:
    return [p.strip() for p in re.split(r"\n\s*\n", text) if p.strip()]

def wc(text: str) -> int:
    return len(text.split())

def chunk_section_text(section_text: str) -> List[Dict]:
    paragraphs = split_into_paragraphs(section_text)

    chunks = []
    current_words = []
    current_parts = []

    def flush():
        nonlocal current_words, current_parts, chunks
        text = "\n\n".join(current_parts).strip()
        if text:
            chunks.append({
                "text": text,
                "word_count": wc(text)
            })
        current_words = []
        current_parts = []

    for para in paragraphs:
        para_wc = wc(para)

        if para_wc > MAX_CHUNK_WORDS:
            if current_parts:
                flush()

            sentences = re.split(r"(?<=[.!?])\s+", para)
            temp_parts = []
            temp_words = []

            for sent in sentences:
                sent_wc = wc(sent)
                if len(temp_words) + sent_wc <= MAX_CHUNK_WORDS:
                    temp_parts.append(sent)
                    temp_words.extend(sent.split())
                else:
                    if temp_parts:
                        text = " ".join(temp_parts).strip()
                        chunks.append({
                            "text": text,
                            "word_count": wc(text)
                        })
                    temp_parts = [sent]
                    temp_words = sent.split()

            if temp_parts:
                text = " ".join(temp_parts).strip()
                chunks.append({
                    "text": text,
                    "word_count": wc(text)
                })
            continue

        if len(current_words) + para_wc <= TARGET_CHUNK_WORDS:
            current_parts.append(para)
            current_words.extend(para.split())
        else:
            if len(current_words) < MIN_CHUNK_WORDS and len(current_words) + para_wc <= MAX_CHUNK_WORDS:
                current_parts.append(para)
                current_words.extend(para.split())
            else:
                flush()
                current_parts.append(para)
                current_words.extend(para.split())

    if current_parts:
        flush()

    if CHUNK_OVERLAP_WORDS > 0 and len(chunks) > 1:
        new_chunks = []
        for i, ch in enumerate(chunks):
            if i == 0:
                new_chunks.append(ch)
                continue

            prev_words = chunks[i - 1]["text"].split()
            overlap_words = prev_words[-CHUNK_OVERLAP_WORDS:] if len(prev_words) >= CHUNK_OVERLAP_WORDS else prev_words
            new_text = " ".join(overlap_words) + "\n\n" + ch["text"]
            new_chunks.append({
                "text": new_text.strip(),
                "word_count": wc(new_text)
            })
        chunks = new_chunks

    return chunks


chunks = []

for section in sections:
    section_chunks = chunk_section_text(section["text"])

    for ch in section_chunks:
        if not ch["text"].strip():
            continue

        chunks.append({
            "chunk_id": str(uuid.uuid4()),
            "document_id": phase1_output["document_id"],
            "document_name": phase1_output["document_name"],
            "company_name": phase1_output["company_name"],
            "financial_year": phase1_output["financial_year"],
            "report_title": phase1_output["report_title"],
            "section_id": section["section_id"],
            "section_name": section["title"],
            "section_type": section["section_type"],
            "page_start": section["page_start"],
            "page_end": section["page_end"],
            "word_count": ch["word_count"],
            "chunk_text": ch["text"]
        })

chunks = [c for c in chunks if c["chunk_text"].strip() and c["word_count"] > 0]

print("=" * 100)
print("PHASE 2 COMPLETE")
print("=" * 100)
print("Document Name  :", phase1_output["document_name"])
print("Document ID    :", phase1_output["document_id"])
print("Company Name   :", phase1_output["company_name"])
print("Financial Year :", phase1_output["financial_year"])
print("Total Sections :", len(sections))
print("Total Chunks   :", len(chunks))

print("\nFirst Chunk Metadata")
print("Chunk ID       :", chunks[0]["chunk_id"])
print("Section Name   :", chunks[0]["section_name"])
print("Section Type   :", chunks[0]["section_type"])
print("Page Range     :", f'{chunks[0]["page_start"]} - {chunks[0]["page_end"]}')
print("Word Count     :", chunks[0]["word_count"])

print("\nFirst Chunk Preview\n")
print(chunks[0]["chunk_text"][:2000])

phase2_sections_path = NOTEBOOK_RECORDS_DIR / "phase2_sections.json"
phase2_chunks_path = NOTEBOOK_RECORDS_DIR / "phase2_chunks.json"
phase2_chunks_csv_path = NOTEBOOK_RECORDS_DIR / "phase2_chunks_review.csv"

with open(phase2_sections_path, "w", encoding="utf-8") as f:
    json.dump(sections, f, ensure_ascii=False, indent=2)

with open(phase2_chunks_path, "w", encoding="utf-8") as f:
    json.dump(chunks, f, ensure_ascii=False, indent=2)

pd.DataFrame(chunks).to_csv(phase2_chunks_csv_path, index=False, encoding="utf-8")

print("\nPhase 2 outputs saved to:")
print("-", phase2_sections_path)
print("-", phase2_chunks_path)
print("-", phase2_chunks_csv_path)

print("\nSection Type Distribution")
print(pd.DataFrame(sections)["section_type"].value_counts(dropna=False))

print("\nChunk Word Count Summary")
print(pd.DataFrame(chunks)["word_count"].describe())

Detected contents/index pages: [9]
Parsed contents entries: 16

Raw contents page preview:

====================================================================================================
CONTENTS PAGE 9
----------------------------------------------------------------------------------------------------
VII
Annual Report 2024 - 25
CONTENTS
HMT LIMITED
Board of Directors.....................................................................................................................1
Performance Highlights.............................................................................................................2
Directors’ Report.......................................................................................................................3
Annual Report on CSR Activities.............................................................................................14
Management Discussions and Analysis..................................................................................19
Report on Corporate Governance...........................................................................................23
Certificate on Corporate Governance.....................................................................................40
Secretarial Audit Report of HMT Limited.................................................................................47
Secretarial Audit Report of HMT Machine Tools Limited.........................................................54
Secretarial Audit Report of HMT (International) Limited..........................................................58
CEO & CFO Certificate...........................................................................................................66
Independent Auditor’s Report.................................................................................................68
Comments of C & AG..............................................................................................................86
Significant Accounting Policies................................................................................................87
Balance Sheet.........................................................................................................................98
Profit & Loss Account............................................................................................................100
Cash Flow Statement............................................................................................................102
Notes Forming Part of Standalone Financial Statement.......................................................105
Consolidated Financial Statement........................................................................................145

Sample parsed entries:
- Board of Directors -> 1
- Performance Highlights -> 2
- Directors’ Report -> 3
- Annual Report on CSR Activities -> 14
- Management Discussions and Analysis -> 19
- Report on Corporate Governance -> 23
- Certificate on Corporate Governance -> 40
- Secretarial Audit Report of HMT Limited -> 47
- Secretarial Audit Report of HMT Machine Tools Limited -> 54
- Secretarial Audit Report of HMT (International) Limited -> 58
- CEO & CFO Certificate -> 66
- Independent Auditor’s Report -> 68
- Comments of C & AG -> 86
- Significant Accounting Policies -> 87
- Notes Forming Part of Standalone Financial Statement -> 105

Final sections after validation: 14
  3-13  | board_report           | Directors’ Report
 14-18  | esg                    | Annual Report on CSR Activities
 19-22  | management_discussion  | Management Discussions and Analysis
 23-39  | governance             | Report on Corporate Governance
 40-46  | governance             | Certificate on Corporate Governance
 47-53  | audit_report           | Secretarial Audit Report of HMT Limited
 54-57  | audit_report           | Secretarial Audit Report of HMT Machine Tools Limited
 58-65  | audit_report           | Secretarial Audit Report of HMT (International) Limited
 66-67  | compliance_certificate | CEO & CFO Certificate
 68-85  | audit_report           | Independent Auditor’s Report
 86-86  | audit_report           | Comments of C & AG
 87-104 | financial_statements   | Significant Accounting Policies
105-144 | financial_statements   | Notes Forming Part of Standalone Financial Statement
145-241 | financial_statements   | Consolidated Financial Statement
====================================================================================================
PHASE 2 COMPLETE
====================================================================================================
Document Name  : Annual-Report-2024-25.pdf
Document ID    : cac28f9d866d468b9b958ee01d9366e6
Company Name   : HMT Limited
Financial Year : 2024-25
Total Sections : 14
Total Chunks   : 486

First Chunk Metadata
Chunk ID       : 4ef77baa-815a-425b-8cbd-b9c513bb1a0e
Section Name   : Directors’ Report
Section Type   : board_report
Page Range     : 3 - 13
Word Count     : 258

First Chunk Preview

I
Annual Report 2024 - 25 Chairman’s Address 72nd Annual General Meeting of HMT Limited My Dear Shareholders, I am honored to present to you the Annual Report of HMT Limited for the year 2024-25. We shall reflect on the past year’s achievements and challenges. It is also imperative to acknowledge the global outlook, the state of the Indian Economy, and the impact of manufacturing initiatives on the future of our nation. Global Outlook The global economy is entering a phase of modest but uneven expansion. According to the IMF’s World Economic Outlook (April 2025), world GDP growth is expected to edge up slightly from 3.2 percent in 2024 to 3.3 percent in 2025, with headline inflation continuing its gradual decline despite lingering upside risks from trade tensions and tighter monetary policy in several advanced economies. Global trade growth, however, is forecast to slow markedly to just 1.7 percent in 2025 reflecting both supply-chain reconfiguration and rising policy uncertainty, which together may dampen investment and cross-border demand over the near term. Indian Economy India’s economic outlook from 2025 to 2030 is robust and optimistic, with GDP growth projected around 6.2-6.7% annually. India is expected to surpass Japan to become the world’s third-largest economy by 2030, reaching a GDP of about $7.3 trillion. Key growth drivers include strong domestic demand, rising private consumption, increased investment, and a digitally skilled workforce. Inflation is moderating, providing the Central Bank room to support growth. Structural reforms, improved trade policies, and a growing middle class are expected to boost consumption and export growth.

Phase 2 outputs saved to:
- /home/yash/Dev_Projects/notebook_records/phase2_sections.json
- /home/yash/Dev_Projects/notebook_records/phase2_chunks.json
- /home/yash/Dev_Projects/notebook_records/phase2_chunks_review.csv

Section Type Distribution
section_type
audit_report              5
financial_statements      3
governance                2
board_report              1
esg                       1
management_discussion     1
compliance_certificate    1
Name: count, dtype: int64

Chunk Word Count Summary
count    486.000000
mean     197.625514
std       70.449278
min       32.000000
25%      147.000000
50%      203.000000
75%      264.000000
max      371.000000
Name: word_count, dtype: float64

In [ ]:
#Add a quick Phase 2 quality summary

print("\nSection Type Distribution")
print(pd.DataFrame(sections)["section_type"].value_counts(dropna=False))

print("\nChunk Word Count Summary")
print(pd.DataFrame(chunks)["word_count"].describe())

In [8]:
# ==========================================
# PHASE 3 — EMBEDDINGS + RETRIEVAL
# ==========================================

chunks_df = pd.DataFrame(chunks).copy()

print("Chunks shape:", chunks_df.shape)
display(chunks_df.head(3))

Chunks shape: (486, 13)

,chunk_id,document_id,document_name,company_name,financial_year,report_title,section_id,section_name,section_type,page_start,page_end,word_count,chunk_text
0,4ef77baa-815a-425b-8cbd-b9c513bb1a0e,cac28f9d866d468b9b958ee01d9366e6,Annual-Report-2024-25.pdf,HMT Limited,2024-25,Annual Report 2024 - 25,485cb01e-71ea-4955-afdc-bf9411ce2830,Directors’ Report,board_report,3,13,258,I\nAnnual Report 2024 - 25 Chairman’s Address ...
1,e386b3b5-fc8b-46ba-bf97-4417db70e4ff,cac28f9d866d468b9b958ee01d9366e6,Annual-Report-2024-25.pdf,HMT Limited,2024-25,Annual Report 2024 - 25,485cb01e-71ea-4955-afdc-bf9411ce2830,Directors’ Report,board_report,3,13,286,"workforce. Inflation is moderating, providing ..."
2,612a15c8-c203-47e8-a1f2-6dbd3f86d1f3,cac28f9d866d468b9b958ee01d9366e6,Annual-Report-2024-25.pdf,HMT Limited,2024-25,Annual Report 2024 - 25,485cb01e-71ea-4955-afdc-bf9411ce2830,Directors’ Report,board_report,3,13,281,it well to remain among the fastest-growing la...

In [9]:
def build_embedding_text(row) -> str:
    parts = [
        f"Company: {row['company_name']}",
        f"Report Title: {row['report_title']}",
        f"Financial Year: {row['financial_year']}",
        f"Section Name: {row['section_name']}",
        f"Section Type: {row['section_type']}",
        f"Page Range: {row['page_start']} to {row['page_end']}",
        "Content:",
        row["chunk_text"]
    ]
    return "\n".join(parts)

chunks_df["embedding_text"] = chunks_df.apply(build_embedding_text, axis=1)

print("Embedding text sample:\n")
print(chunks_df.loc[0, "embedding_text"][:2500])

Embedding text sample:

Company: HMT Limited
Report Title: Annual Report 2024 - 25
Financial Year: 2024-25
Section Name: Directors’ Report
Section Type: board_report
Page Range: 3 to 13
Content:
I
Annual Report 2024 - 25 Chairman’s Address 72nd Annual General Meeting of HMT Limited My Dear Shareholders, I am honored to present to you the Annual Report of HMT Limited for the year 2024-25. We shall reflect on the past year’s achievements and challenges. It is also imperative to acknowledge the global outlook, the state of the Indian Economy, and the impact of manufacturing initiatives on the future of our nation. Global Outlook The global economy is entering a phase of modest but uneven expansion. According to the IMF’s World Economic Outlook (April 2025), world GDP growth is expected to edge up slightly from 3.2 percent in 2024 to 3.3 percent in 2025, with headline inflation continuing its gradual decline despite lingering upside risks from trade tensions and tighter monetary policy in several advanced economies. Global trade growth, however, is forecast to slow markedly to just 1.7 percent in 2025 reflecting both supply-chain reconfiguration and rising policy uncertainty, which together may dampen investment and cross-border demand over the near term. Indian Economy India’s economic outlook from 2025 to 2030 is robust and optimistic, with GDP growth projected around 6.2-6.7% annually. India is expected to surpass Japan to become the world’s third-largest economy by 2030, reaching a GDP of about $7.3 trillion. Key growth drivers include strong domestic demand, rising private consumption, increased investment, and a digitally skilled workforce. Inflation is moderating, providing the Central Bank room to support growth. Structural reforms, improved trade policies, and a growing middle class are expected to boost consumption and export growth.

In [10]:
#Load Embedding Model
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

print("Loading embedding model:", EMBEDDING_MODEL_NAME)
embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
print("Model loaded successfully.")

Loading embedding model: all-MiniLM-L6-v2

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 13965.20it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Model loaded successfully.

In [11]:
#Generate chunk embeddings

chunk_texts_for_embedding = chunks_df["embedding_text"].tolist()

chunk_embeddings = embedding_model.encode(
    chunk_texts_for_embedding,
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print("Chunk embeddings shape:", chunk_embeddings.shape)

Batches: 100%|██████████| 16/16 [00:05<00:00,  3.03it/s]

Chunk embeddings shape: (486, 384)

In [12]:
#Save embedding artifacts

phase3_embeddings_path = NOTEBOOK_RECORDS_DIR / "phase3_chunk_embeddings.npy"
phase3_chunks_enriched_path = NOTEBOOK_RECORDS_DIR / "phase3_chunks_enriched.csv"

np.save(phase3_embeddings_path, chunk_embeddings)
chunks_df.to_csv(phase3_chunks_enriched_path, index=False, encoding="utf-8")

print("Phase 3 embedding artifacts saved:")
print("-", phase3_embeddings_path)
print("-", phase3_chunks_enriched_path)

Phase 3 embedding artifacts saved:
- /home/yash/Dev_Projects/notebook_records/phase3_chunk_embeddings.npy
- /home/yash/Dev_Projects/notebook_records/phase3_chunks_enriched.csv

In [13]:
#Query embedding helper

def embed_query(query: str) -> np.ndarray:
    query_embedding = embedding_model.encode(
        [query],
        convert_to_numpy=True,
        normalize_embeddings=True
    )
    return query_embedding[0]

In [14]:
#Simple retrieval

def retrieve_top_k_chunks(query: str, top_k: int = TOP_K) -> pd.DataFrame:
    query_vec = embed_query(query)
    scores = cosine_similarity([query_vec], chunk_embeddings)[0]

    result_df = chunks_df.copy()
    result_df["retrieval_score"] = scores

    result_df = result_df.sort_values(
        by="retrieval_score",
        ascending=False
    ).head(top_k).reset_index(drop=True)

    return result_df

In [15]:
#First retrieval test

test_query = "What are the main CSR activities carried out by the company?"

top_results = retrieve_top_k_chunks(test_query, top_k=5)

display(
    top_results[
        [
            "chunk_id",
            "section_name",
            "section_type",
            "page_start",
            "page_end",
            "word_count",
            "retrieval_score"
        ]
    ]
)

,chunk_id,section_name,section_type,page_start,page_end,word_count,retrieval_score
0,c20b9834-a0e4-40ff-a909-0b125a1231e6,Report on Corporate Governance,governance,23,39,174,0.633742
1,40f046f7-f731-4a6d-b614-3519b6820521,Report on Corporate Governance,governance,23,39,285,0.593922
2,13bc30d1-fdf8-4899-839e-ff2c8a979089,Report on Corporate Governance,governance,23,39,264,0.577060
3,2b97bac3-383e-4c17-a3a9-6795e821d42d,Report on Corporate Governance,governance,23,39,216,0.572055
4,f9d83257-a640-49a4-9891-04d4b6ab67f9,Report on Corporate Governance,governance,23,39,127,0.547616

In [16]:
#Retrieval preview helper

def show_retrieval_results(query: str, top_k: int = 5, preview_chars: int = 1200):
    results = retrieve_top_k_chunks(query, top_k=top_k)

    print("=" * 120)
    print("QUERY:", query)
    print("=" * 120)

    for idx, row in results.iterrows():
        print(f"\nRank #{idx + 1}")
        print("-" * 120)
        print("Score       :", round(row["retrieval_score"], 4))
        print("Section     :", row["section_name"])
        print("Type        :", row["section_type"])
        print("Pages       :", f'{row["page_start"]} - {row["page_end"]}')
        print("Word Count  :", row["word_count"])
        print("Chunk ID    :", row["chunk_id"])
        print("\nPreview:\n")
        print(row["chunk_text"][:preview_chars])
        print("\n")

In [17]:
#Few tests

show_retrieval_results("What are the main CSR activities carried out by the company?", top_k=5)
show_retrieval_results("Summarize the management discussion and analysis section.", top_k=5)
show_retrieval_results("What does the report say about corporate governance?", top_k=5)
show_retrieval_results("What observations are mentioned in the audit report?", top_k=5)
show_retrieval_results("What do the financial statements say about the company?", top_k=5)

========================================================================================================================
QUERY: What are the main CSR activities carried out by the company?
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.6337
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 174
Chunk ID    : c20b9834-a0e4-40ff-a909-0b125a1231e6

Preview:

undertaken by the Company as specified in Schedule VII of the Companies Act and the expenditure thereon, excluding activities undertaken in pursuance of normal course of business of the Company.

c) The CSR projects or programs or activities that benefit only the employees of the company and their families shall not be considered as CSR activities in accordance with section 135 of the Act. d) The CSR and Sustainability budget expenditure shall be fixed in accordance with the provisions of the Act, Rules and the Guidelines. e) The Company will endeavor at all times to build and develop the skills of its CSR team and enhance level of CSR awareness within the organization. f) Execution of CSR projects can be taken up generally by in-house teams or through suitable partnerships with State Governments, PSUs, NGOs, Private Companies. As far as possible, HMT’s manpower should be committed only for monitoring and supervision. g) To assist and take up CSR activities forward, the Corporate CSR Committee & Unit CSR Committee (on need basis) has been constituted.



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5939
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 285
Chunk ID    : 40f046f7-f731-4a6d-b614-3519b6820521

Preview:

per cent of the average net profit as per subsection (5) of section 135: N/A Date: 29.09.2025 Sd/- Rajesh Kohli {Chairman & Managing Director (Addl. Charge)} & (Chairperson, CSR Committee)

Annual Report 2024 - 25 Annexure-1A
DETAILS OF THE CSR ACTIVITIES UNDERTAKEN DURING FY2024-25
(Status of Ongoing & other than Ongoing CSR projects) Sl. No. CSR Amount allocated as on 31.03.2025 (In Rs.) CSR Amount incurred on completion of project (In Rs.) Name of the Project Item from the list of activities in Schedule VII to the Act Location of the project Mode of Imple mentation Project duration / Date of Completion *Rs. 24,39,740 approx. Inclusive of miscellaneous expenses subject to actual Rs.23,55,740.20 Contribution of GeneXpert 4/4 Module 10 Optic Channel Cartridge Based Nucleic Acid Amplification Test (CBNAAT) Machine to Government District TB Center, Mandya, Karnataka Item No. I (Health Care) Mandya, Karnataka Direct 30.09.2025 Ongoing project completed on 19.04.2025 *Rs. 3,53,500 approx. Inclusive of miscellaneous expenses subject to actual Rs.3,34,500.00 Contribution of One Medical Equipment 2-Channel Electrotherapy with laser and Ultrasound to M/s. Shri Guruji Seva Nyas Item No. I (



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5771
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 264
Chunk ID    : 13bc30d1-fdf8-4899-839e-ff2c8a979089

Preview:

1. Brief Outline on CSR Policy of the Company: CSR Vision: To contribute the sustainable development and inclusive growth while taking care of People, Planet and organizational goals / growth.

CSR Mission a) To become socially responsible corporate entity committed to improving the quality of life of the society at large. b) To create and develop facilities for the communities we engage with. c) To balance economic, environmental and welfare development objectives through collective and unified effort of all stakeholders. Objective: The policy is framed with the objective(s) stated herein below: a) To provide framework for carrying out the CSR projects or programs or activities including the modalities of execution and transparent monitoring mechanism for its implementation undertaken by the Company which is within the scope of the Companies Act 2013 and the rules made therein; the DPE Guidelines, as amended from time to time; b) To create awareness on CSR practices across all the levels in the Company, operate its business in an economically, socially & environmentally sustainable manner, while recognizing the interests of all its stakeholders. c) Through its CSR Initiatives, gen



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5721
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 216
Chunk ID    : 2b97bac3-383e-4c17-a3a9-6795e821d42d

Preview:

be committed only for monitoring and supervision. g) To assist and take up CSR activities forward, the Corporate CSR Committee & Unit CSR Committee (on need basis) has been constituted.

Annual Report 2024 - 25
2. Composition of CSR Committee:
Sl. No. Name of Director Designation / Nature of Directorship Number of meetings of CSR Committee held during the year Number of meetings of CSR Committee attended during the year Shri. Rajesh Kohli1 Chairperson / Chairman & Managing Director (Addl. Charge) Shri. Krishnaswami Ravishankar2 Chairperson / Chairman & Managing Director (Addl. Charge) - - Ms. Arti Bhatnagar3 Member / Govt. Nominee Director - - Dr. Renuka Mishra4 Member / Govt. Nominee Director Ms. Mukta Shekhar5 Member / Govt. Nominee Director Smt. Sameena Kohli6 Member / Director (Finance) (Addl. Charge) Ms. Rita Saxena7 Member / Director (Finance) (Addl. Charge)
1. Appointed as Chairperson w.e.f. 05.04.2024
2. Ceased to be Chairperson w.e.f. 05.04.2024
3. Appointed as Member w.e.f. 25.05.2024 and Ceased to be Member w.e.f. 10.06.2024
4. Appointed as Member w.e.f. 23.07.2024
5. Ceased to be Member w.e.f. 23.07.2024
6. Appointed as Member w.e.f. 10.06.2024
7. Ceased to be Member w.



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5476
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 127
Chunk ID    : f9d83257-a640-49a4-9891-04d4b6ab67f9

Preview:

be Member w.e.f. 24.05.2024 3. Provide the web-link where Composition of CSR committee, CSR Policy and CSR projects approved by the board are disclosed on the website of the company.

Committee Composition: https://www.hmtindia.com/investor-relation/share-holder-information/

CSR Policy: https://www.hmtindia.com/policies/

CSR Projects: https://www.hmtindia.com/investor-relation/csr/ 4. Provide the executive summary along with web-link(s) of Impact Assessment of CSR Projects carried out in pursuance of sub-rule (3) of rule 8, if applicable.

Not applicable 5. (a) Average net profit of the company as per sub-section (5) of section 135: Rs. 23,57,55,121/- (b) Two percent of average net profit of the company as per sub-section (5) of section 135: Rs. 47,15,103/-

Annual Report 2024 - 25 (c) Surplus arising out of the CSR projects or programs or activities of the previous financial years:
NIL #


========================================================================================================================
QUERY: Summarize the management discussion and analysis section.
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4783
Section     : Consolidated Financial Statement
Type        : financial_statements
Pages       : 145 - 241
Word Count  : 232
Chunk ID    : d6cea2a4-4525-4052-9dd6-a3b1c95f9b91

Preview:

exceeding 10% of revenue from operations A) India Food Processing Unit 114.21 2,679.58 Machine Tools 4,092.64 3,118.03 Total 4,206.85 5,386.31 B) Outside India - - Total (A +B) 4,206.85 5,386.31

NOTES FORMING PART OF CONSOLIDATED FINANCIAL STATEMENTS

Annual Report 2024 - 25
NOTES FORMING PART OF CONSOLIDATED FINANCIAL STATEMENTS
50 Ratio Analysis Ratio Numerator Denominator
FY 2024-25
FY 2023-24
% Variance Reason for Variance Current Ratio Current Assets Current Liabilities 0.21 0.25 -16.11% - Debt-Equity Ratio Total Debt Shareholder's Equity - - - - Debt Service Coverage Ratio Earnings available for debt service(EBITDA) Debt service (Interest + Principal) -0.06 -0.05 10.76% - Return on Equity Ratio Net Profit after taxes Average Shareholder's equity - - - - Inventory turnover ratio Sales Average Inventory 1.34 1.40 -4.22% - Trade Receivables turnover ratio Credit Sales Average Trade receivables 1.10 1.02 8.04% - Trade payables turnover ratio Net Credit Purchases/ Services Average Trade Payables 0.67 1.06 -36.99% Due to reduction in the credit purchases Net capital turnover ratio Net Sales Average Working Capital -0.08 -0.05 60.00% Due to decrease in net sales and decrease in the



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4293
Section     : Certificate on Corporate Governance
Type        : governance
Pages       : 40 - 46
Word Count  : 290
Chunk ID    : b9a0664f-6f1d-41e1-bf40-e3610cb5f2e0

Preview:

was retained with available Directors as there was no Independent Directors during the FY 2024-25. The terms of reference of the Risk Management Committee are as enumerated under the provisions

Annual Report 2024 - 25 of the SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015 which includes formulation of detailed risk management policy, to ensure appropriate methodology, processes and systems are in place to monitor and evaluate risks associated with the business of the Company, to monitor and oversee implementation of the risk management policy, including evaluating the adequacy of risk management systems, etc. During the year 2024-25, Two (2) Risk Management Committee Meetings were held on July 26 in the calendar year 2024 and February 14 in the calendar year 2025. Details of attendance of members at the Risk Management Committee Meeting held during 2024-25 Name of the Member Category Meetings held during respective tenure of Directors No of Meetings attended Shri. Rajesh Kohli1
C & MD
Shri. Krishnaswami Ravishankar2
C & MD
- - Dr. Renuka Mishra3
NENI
Ms. Mukta Shekhar4
NENI
- - Shri. S.K. Kadbe
GM(O&M)
1. Appointed as Member w.e.f. 05.04.2024
2. Ceased to



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4287
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 271
Chunk ID    : 174dbf25-e1a2-4273-bd1e-fec4739f06e4

Preview:

- Krishnaswami Ravishankar (DIN: 10540509) (upto 05.04.2024) C & MD - - NA - Arti Bhatnagar (DIN: 10065528) NENI - Renuka Mishra (DIN: 08635835) (w.e.f. 23.07.2024) NENI Yes - -

Annual Report 2024 - 25 Mukta Shekhar
(DIN: 10118859)
(upto 23.07.2024)
NENI
NA
- - Sameena Kohli
(DIN: 10663362)
(w.e.f. 10.06.2024)
ENI
- - - - Rita Saxena
(DIN: 10294769)
(upto 24.05.2024)
ENI
NA
- - - C & MD: Chairman & Managing Director, ENI: Executive & Non-Independent, NENI: Non-Executive & Non- Independent, NEI: Non-Executive & Independent # Pursuant to Regulation 26 of the Listing Regulations, the Chairmanship / Membership of Audit Committee and Stakeholders’ Relationship Committee in Public Limited Companies are considered. No Director is holding equity shares in the Company as on 31.03.2025. None of the Directors had any relationship inter-se during the year 2024-25. Details of Directors holding Directorship in other Listed Entities and the category of their Directorship as on 31.03.2025: Name of Director Name of Other Listed Entity where Directorship is held Category of Directorship Arti Bhatnagar Bharat Heavy Electricals Limited
NENI
MMTC Limited
NENI
The State Trading Corporation of India Lim



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4246
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 272
Chunk ID    : 28a3ac26-6377-48a9-b068-b31e0b9dd130

Preview:

UNLISTED MATERIAL SUBSIDIARY Pursuant to the provisions of Regulation 24A of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015, the Secretarial Audit Report for

Annual Report 2024 - 25 the Financial Year 2024-25 of HMT Machine Tools Limited & HMT (International) Limited, an Unlisted Material Subsidiaries of the Company along with replies to observations are appended as Annexure-7, 7A, 8 & 8A to this report. BUSINESS RESPONSIBILITY AND SUSTAINABILITY
REPORT (BRSR)
As per BSE circular no. 20240510-48 & NSE circular no. NSE/CML/2024/11 dated: May 10, 2024, the BRSR can be provided as a LINK in the Annual Report of the Company instead of publishing the whole report. As such the BRSR 2024-25 can be accessed from the link https://www.hmtindia.com/business- responsibility-and-sustainability-report/
EVALUATION OF THE PERFORMANCE OF
BOARD
Being a Government Company, HMT is exempted in terms of the MCA Notifications dated June 5, 2015 & July 5, 2017, from the evaluation of performance of all members of the Board of the Company which is being done by the Administrative Ministry i.e., the Ministry of Heavy Industries and/or by the D



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4215
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 73
Chunk ID    : b33a364e-068a-41dc-a7c6-17f668c48c60

Preview:

of building a world class HMT. For and on behalf of the Board of Directors Sd/- (Rajesh Kohli) Place: Bengaluru Date: 29.09.2025 Chairman & Managing Director (Addl. Charge) DIN: 10333951

Annual Report 2024 - 25 Annexure - 1
ANNUAL REPORT ON CSR ACTIVITIES
1. Brief Outline on CSR Policy of the Company:

CSR Vision: To contribute the sustainable development and inclusive growth while taking care of People, Planet and organizational goals / growth.


========================================================================================================================
QUERY: What does the report say about corporate governance?
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.642
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 266
Chunk ID    : 4199238d-997a-41a8-ac67-9f2b328b548a

Preview:

Company during the year, remained cordial. For and on behalf of the Board of Directors Sd/- (Rajesh Kohli) Place: Bengaluru Date: 29.09.2025 Chairman & Managing Director (Addl. Charge) DIN: 10333951

Annual Report 2024 - 25
ANNEXURE- 3
REPORT ON CORPORATE GOVERNANCE
I
COMPANY’S PHILOSOPHY
In compliance with Regulation 17 of SEBI (LODR) Regulation, 2015 and as per the applicable provisions of the Companies Act, 2013 as amended from time to time, your Directors submit their report on the matters mentioned in the said Regulation and practice followed by the Company. The Company has a “Code of Conduct for Board Members and Senior Management’ i.e., Chairman and Managing Directors, all Directors, Executive Directors and General Managers. The Company has been following good Corporate Governance practices like striking reasonable balance in the composition of the Board of Directors, setting up of Audit Committee and other Committees, adequate disclosure of information and business to be deliberated by the Board, etc. II
BOARD OF DIRECTORS
As per the listing requirements, the Board of Directors of the Company should consist of minimum Six Directors out of which half shall comprise of Indepe



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.588
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 71
Chunk ID    : a68fe630-f733-4894-9387-b9d65aed392e

Preview:

Amount of CSR amount spent Details of entity/ Authority/ beneficiary of the registered owner (1) (2) (3) (4) (5) (6) CSR Registration Number, if applicable Name Registered address N/A 9.

Specify the reason(s), if the company has failed to spend two per cent of the average net
profit as per subsection (5) of section 135: N/A Date: 29.09.2025 Sd/- Rajesh Kohli {Chairman & Managing Director (Addl. Charge)} & (Chairperson, CSR Committee)



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.575
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 290
Chunk ID    : 18fdd00c-03bf-4234-80e3-f2132aee4784

Preview:

be the Convener of the Committee Meetings. On the spirit of the law, Audit Committee was retained with available Directors as there was no Independent Directors during the FY 2024-25.

Annual Report 2024 - 25 In terms of section 177(8) of the Companies Act, 2013, the Board accepted all the recommendations made by the Audit Committee during the year. The terms of reference of Audit Committee are as enumerated under the provisions of the Companies Act, 2013, SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015 and the DPE guidelines on Corporate Governance which includes Oversight of the Company’s financial reporting process and the disclosure of its financial information to ensure that the financial statement is correct, sufficient and credible, recommendation of remuneration of statutory auditors appointed by
CAG,
recommendation for appointment, remuneration and terms of appointment of internal auditors, approval of payment to statutory auditors for any other services rendered by the statutory auditors, reviewing, with the management, the annual financial statements and auditor’s report thereon before submission to the board for approval, reviewing, with the man



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5646
Section     : Secretarial Audit Report of HMT Limited
Type        : audit_report
Pages       : 47 - 53
Word Count  : 260
Chunk ID    : 21f229ba-f17e-42c0-858d-1d91e2d869f9

Preview:

Bengaluru - 560 032, Karnataka, India For and on behalf of the Board of Directors Sd/- Rajesh Kohli) Place: Bengaluru Date: 29.09.2025 Chairman & Managing Director (Addl. Charge) DIN: 10333951

Annual Report 2024 - 25 Annexure- 3A
CERTIFICATE ON CORPORATE GOVERNANCE

In [22]:
def infer_section_filter_from_query(query: str):
    q = query.lower()

    section_map = {
        "esg": ["csr", "sustainability", "esg", "social responsibility", "brsr"],
        "management_discussion": ["management discussion", "management analysis", "md&a", "outlook", "performance review"],
        "governance": ["corporate governance", "governance"],
        "audit_report": ["audit", "auditor", "secretarial audit", "independent auditor"],
        "financial_statements": ["financial statements", "balance sheet", "profit and loss", "cash flow", "assets", "liabilities", "notes to accounts"],
        "board_report": ["directors report", "director's report", "board report"],
        "compliance_certificate": ["ceo cfo certificate", "compliance certificate", "certificate"],
        "leadership_message": ["chairman message", "chairman's message", "chairman address"],
        "highlights": ["performance highlights", "highlights"]
    }

    matched_types = []
    for section_type, keywords in section_map.items():
        if any(keyword in q for keyword in keywords):
            matched_types.append(section_type)

    return matched_types if matched_types else None


def retrieve_top_k_chunks_filtered(query: str, top_k: int = TOP_K) -> pd.DataFrame:
    query_vec = embed_query(query)
    scores = cosine_similarity([query_vec], chunk_embeddings)[0]

    result_df = chunks_df.copy()
    result_df["retrieval_score"] = scores

    section_filters = infer_section_filter_from_query(query)

    if section_filters:
        filtered_df = result_df[result_df["section_type"].isin(section_filters)].copy()
        if not filtered_df.empty:
            result_df = filtered_df

    result_df = result_df.sort_values("retrieval_score", ascending=False).head(top_k).reset_index(drop=True)
    return result_df


def show_retrieval_results_filtered(query: str, top_k: int = 5, preview_chars: int = 1200):
    section_filters = infer_section_filter_from_query(query)
    results = retrieve_top_k_chunks_filtered(query, top_k=top_k)

    print("=" * 120)
    print("QUERY:", query)
    print("SECTION FILTERS:", section_filters)
    print("=" * 120)

    for idx, row in results.iterrows():
        print(f"\nRank #{idx + 1}")
        print("-" * 120)
        print("Score       :", round(row["retrieval_score"], 4))
        print("Section     :", row["section_name"])
        print("Type        :", row["section_type"])
        print("Pages       :", f"{row['page_start']} - {row['page_end']}")
        print("Word Count  :", row["word_count"])
        print("\nPreview:\n")
        print(row["chunk_text"][:preview_chars])
        print("\n")

In [23]:
show_retrieval_results_filtered(
    "What are the main CSR activities carried out by the company?",
    top_k=5
)

========================================================================================================================
QUERY: What are the main CSR activities carried out by the company?
SECTION FILTERS: ['esg']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5222
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 252

Preview:

complied with provisions relating to the constitution of Internal Complaints Committee under the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 and following information are submitted.

i. Number of complaints of sexual harassment received in the year - NIL ii. Number of complaints disposed off during the year - NIL iii. Number of cases pending for more than ninety days – NIL
FRAUD REPORTING
There was no incident of fraud reported during the year under review. CORPORATE SOCIAL RESPONSIBILITY (CSR)
The Board level CSR Committee was constituted on 12th August 2019. The composition of the CSR Committee is provided in the Corporate Governance Report. The CSR policy is placed on the website of the Company at https://www.hmtindia.com/ policies/. The average net profits of the Company during the three immediately preceding financial years is Rs.2357.55 Lakhs, as such, the Company is required to spend at least two per cent of Rs.2357.55 Lakhs, i.e., Rs.47.15 Lakhs on CSR activities during the FY2024-25 as per the provisions of section 135 (5) of the Companies Act, 2013. The CSR Annual report for FY 2024-25 is provided as Annexure-1 in the format p



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4335
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 55

Preview:

Hindi Word of the Day is displayed prominently, and Hindi newspapers are procured daily to encourage employees to use the Official Language. Employees are also encouraged to sign in Hindi.

Further, Hindi Officers and executives actively participate in meetings, programmes, online webinars, and Hindi Month celebrations organized by the Town Official Language Implementation Committee (TOLIC).



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4288
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 249

Preview:

expenses as closure activities under process. B. ASSOCIATE /JOINT VENTURE COMPANY SUDMO-HMT Process Engineers (India) Limited The Joint Venture Company could not transact any business during the year under review.

For the Financial Year 2024-25, this company incurred Net Loss of Rs.0.99 lakhs Gujarat State Machine Tools Corporation Limited (GSMTC) This Associate Company between HMT Limited and GIIC Limited discontinued its operations since long. Now, the Board of Directors of GIIC Limited has approved for liquidation of GSMTC which will be subject to approval from Government of Gujarat. The Board of Directors of the Company has also approved in-principle for Liquidation of GSMTC subject to the approval of the Administrative Ministry. Matter is under process. Salient features of the financial statement of subsidiaries/associate companies/joint ventures are provided in Form AOC-1 in the consolidated financial statements for the FY2024-25. INDIAN ACCOUNTING STANDARDS
The Financial Statements have been prepared to comply in all material aspects with the Indian Accounting Standards (“Ind AS”) notified under section 133 of the Companies Act, 2013 read with Companies (Indian Accounting S



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4077
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 275

Preview:

from Rs.1204.09 Crores to Rs.355.60 Crores by reduction of 848490000 Equity Shares of Rs.10/- each held by President of India (as per the Cabinet Approval). Registrar of Companies, Karnataka (ROC)

Annual Report 2024 - 25 has registered the NCLT order on 17.11.2018 and issued “Certificate of Registration confirming the Reduction of Share Capital of HMT Ltd”. However, the process of reduction of share capital in the records of Stock Exchanges and Depositories is pending for procedural compliances which are under process in consultation with Registrar and Share Transfer Agent (“RTA”). The shareholding of President of India is 279566626 of Rs.10/- each, equivalent to 78.62% shareholding in the Company as against 1128056626 equity share of Rs.10/- each shown as per RTA records. Hence there is a difference between Paid up Share Capital of the Company as per Audited Financial Statements and Shareholding Pattern provided by RTA. CONSOLIDATED FINANCIAL STATEMENTS
As required under the Companies Act 2013 and SEBI (LODR) Regulation, 2015, Consolidated Financial Statements of the Company along with that of the Subsidiaries for the financial year 2024-25, conforming to the applicable Accountin



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4047
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 289

Preview:

and other information of each of the Subsidiary Companies will be available for inspection by any member at the Registered Office of the Company & on the Company’s website www.hmtindia.com.

HUMAN RESOURCES
The employee strength of the Company (HMT Limited) as on March 31, 2025, stood at 45 Nos. comprising of various categories of employees in manufacturing plants and other offices. The number of employees on the rolls of the Company as on March 31, 2025 in SC/ST, Ex- servicemen, Physically Handicapped and Women Employee Categories etc. is detailed below: Scheduled Castes Scheduled Tribes Other Backward Classes Ex-Servicemen Persons with Disabilities Women employees Minorities
PERSONNEL AND INDUSTRIAL RELATIONS
The Personnel and Industrial Relations situation in the Company during the year, remained cordial. IMPLEMENTATION OF OFFICIAL LANGUAGE
The Company continues to make consistent efforts to implement the Official Language Act, Rules, and Policy as per the directives of the Government, with the objective of enhancing the use of Hindi in all operations. An Official Language Implementation Committee has been constituted at the Units, Subsidiaries, and the Corporate Office, Bengalu

In [19]:
# #Display Helper

# def show_retrieval_results_filtered(query: str, top_k: int = 5, preview_chars: int = 1200):
#     section_filters = infer_section_filter_from_query(query)
#     results = retrieve_top_k_chunks_filtered(query, top_k=top_k)

#     print("=" * 120)
#     print("QUERY:", query)
#     print("SECTION FILTERS:", section_filters)
#     print("=" * 120)

#     for idx, row in results.iterrows():
#         print(f"\nRank #{idx + 1}")
#         print("-" * 120)
#         print("Score       :", round(row["retrieval_score"], 4))
#         print("Section     :", row["section_name"])
#         print("Type        :", row["section_type"])
#         print("Pages       :", f'{row["page_start"]} - {row["page_end"]}')
#         print("Word Count  :", row["word_count"])
#         print("\nPreview:\n")
#         print(row["chunk_text"][:preview_chars])
#         print("\n")

In [24]:
#Top-k retrieval testing

sample_queries = [
    "What are the main CSR activities carried out by the company?",
    "Summarize the management discussion and analysis section.",
    "What does the report say about corporate governance?",
    "What observations are mentioned in the secretarial audit report?",
    "What does the CEO and CFO certificate mention?",
    "What are the major points in the directors report?",
    "What do the financial statements indicate about the company?",
    "What are the key performance highlights?",
]

In [25]:
#Test each

for query in sample_queries:
    show_retrieval_results_filtered(query, top_k=5, preview_chars=700)

========================================================================================================================
QUERY: What are the main CSR activities carried out by the company?
SECTION FILTERS: ['esg']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5222
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 252

Preview:

complied with provisions relating to the constitution of Internal Complaints Committee under the Sexual Harassment of Women at Workplace (Prevention, Prohibition and Redressal) Act, 2013 and following information are submitted.

i. Number of complaints of sexual harassment received in the year - NIL ii. Number of complaints disposed off during the year - NIL iii. Number of cases pending for more than ninety days – NIL
FRAUD REPORTING
There was no incident of fraud reported during the year under review. CORPORATE SOCIAL RESPONSIBILITY (CSR)
The Board level CSR Committee was constituted on 12th August 2019. The composition of the CSR Committee is provided in the Corporate Governance Report. Th



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4335
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 55

Preview:

Hindi Word of the Day is displayed prominently, and Hindi newspapers are procured daily to encourage employees to use the Official Language. Employees are also encouraged to sign in Hindi.

Further, Hindi Officers and executives actively participate in meetings, programmes, online webinars, and Hindi Month celebrations organized by the Town Official Language Implementation Committee (TOLIC).



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4288
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 249

Preview:

expenses as closure activities under process. B. ASSOCIATE /JOINT VENTURE COMPANY SUDMO-HMT Process Engineers (India) Limited The Joint Venture Company could not transact any business during the year under review.

For the Financial Year 2024-25, this company incurred Net Loss of Rs.0.99 lakhs Gujarat State Machine Tools Corporation Limited (GSMTC) This Associate Company between HMT Limited and GIIC Limited discontinued its operations since long. Now, the Board of Directors of GIIC Limited has approved for liquidation of GSMTC which will be subject to approval from Government of Gujarat. The Board of Directors of the Company has also approved in-principle for Liquidation of GSMTC subject to



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4077
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 275

Preview:

from Rs.1204.09 Crores to Rs.355.60 Crores by reduction of 848490000 Equity Shares of Rs.10/- each held by President of India (as per the Cabinet Approval). Registrar of Companies, Karnataka (ROC)

Annual Report 2024 - 25 has registered the NCLT order on 17.11.2018 and issued “Certificate of Registration confirming the Reduction of Share Capital of HMT Ltd”. However, the process of reduction of share capital in the records of Stock Exchanges and Depositories is pending for procedural compliances which are under process in consultation with Registrar and Share Transfer Agent (“RTA”). The shareholding of President of India is 279566626 of Rs.10/- each, equivalent to 78.62% shareholding in the



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4047
Section     : Annual Report on CSR Activities
Type        : esg
Pages       : 14 - 18
Word Count  : 289

Preview:

and other information of each of the Subsidiary Companies will be available for inspection by any member at the Registered Office of the Company & on the Company’s website www.hmtindia.com.

HUMAN RESOURCES
The employee strength of the Company (HMT Limited) as on March 31, 2025, stood at 45 Nos. comprising of various categories of employees in manufacturing plants and other offices. The number of employees on the rolls of the Company as on March 31, 2025 in SC/ST, Ex- servicemen, Physically Handicapped and Women Employee Categories etc. is detailed below: Scheduled Castes Scheduled Tribes Other Backward Classes Ex-Servicemen Persons with Disabilities Women employees Minorities
PERSONNEL AND


========================================================================================================================
QUERY: Summarize the management discussion and analysis section.
SECTION FILTERS: ['management_discussion']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4246
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 272

Preview:

UNLISTED MATERIAL SUBSIDIARY Pursuant to the provisions of Regulation 24A of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015, the Secretarial Audit Report for

Annual Report 2024 - 25 the Financial Year 2024-25 of HMT Machine Tools Limited & HMT (International) Limited, an Unlisted Material Subsidiaries of the Company along with replies to observations are appended as Annexure-7, 7A, 8 & 8A to this report. BUSINESS RESPONSIBILITY AND SUSTAINABILITY
REPORT (BRSR)
As per BSE circular no. 20240510-48 & NSE circular no. NSE/CML/2024/11 dated: May 10, 2024, the BRSR can be provided as a LINK in the Annual Report of the Company instead



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.4109
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 79

Preview:

Annual Report 2024 - 25
CORPORATE GOVERNANCE
Pursuant to Regulation 34 of the SEBI (LODR) Regulation, 2015, a Report on Corporate Governance is appended as Annexure-3 to this Report along with the Compliance Certificate from the Auditor as Annexure-3A. INFORMATION REGARDING CONSERVATION
OF ENERGY, TECHNOLOGY ABSORPTION AND
FOREIGN EXCHANGE EARNINGS AND OUTGO
Particulars in respect of conservation of energy, technology absorption and foreign exchange earnings and outgo, as required under the Companies (Accounts) Rules, 2014 are appended as Annexure-4.



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.3757
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 202

Preview:

Section 134(3)(a) of the Companies Act, 2013, the Company has placed a copy of the Annual Return as on March 31, 2025 on its website at https://www.hmtindia.com/investor- relation/ar/ AUDITORS M/s.

G R S M & Associates, Chartered Accountants, Bengaluru were appointed as Statutory Auditors of the Company and its Auxiliary Business Division (ABD) for the year 2024-25 by the Comptroller & Auditor General of India. M/s. R K Muley & CO., Chartered Accountants, was also appointed as Branch Auditor for the Food Processing Machinery Division, Aurangabad of the Company. Replies to the observations by the Statutory Auditors in their Report are given as Annexure-5. SECRETARIAL AUDIT REPORT
In terms of



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.3755
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 49

Preview:

Transfer Agents of the Company. No significant and material orders have been passed by any Regulator(s) or Court(s) or Tribunal(s) impacting the going concern status and Company’s operations in future.

As on 31st March 2025, no amount is required to be transferred to Investor Education and Protection Fund (IEPF).



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.3659
Section     : Management Discussions and Analysis
Type        : management_discussion
Pages       : 19 - 22
Word Count  : 292

Preview:

EARNINGS AND OUTGO Particulars in respect of conservation of energy, technology absorption and foreign exchange earnings and outgo, as required under the Companies (Accounts) Rules, 2014 are appended as Annexure-4.

DIRECTORS RESPONSIBILITY STATEMENT
To the best of their knowledge and belief and according to the information and explanations obtained by them, your Directors make the following statements in terms of Section 134(3)(C) of the Companies Act, 2013:  that in the preparation of the annual financial statements for the year ended 31.03.2025, the applicable accounting standards has been followed along with proper explanation relating to material departures;  that such accounting poli


========================================================================================================================
QUERY: What does the report say about corporate governance?
SECTION FILTERS: ['governance']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.642
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 266

Preview:

Company during the year, remained cordial. For and on behalf of the Board of Directors Sd/- (Rajesh Kohli) Place: Bengaluru Date: 29.09.2025 Chairman & Managing Director (Addl. Charge) DIN: 10333951

Annual Report 2024 - 25
ANNEXURE- 3
REPORT ON CORPORATE GOVERNANCE
I
COMPANY’S PHILOSOPHY
In compliance with Regulation 17 of SEBI (LODR) Regulation, 2015 and as per the applicable provisions of the Companies Act, 2013 as amended from time to time, your Directors submit their report on the matters mentioned in the said Regulation and practice followed by the Company. The Company has a “Code of Conduct for Board Members and Senior Management’ i.e., Chairman and Managing Directors, all Directors,



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.588
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 71

Preview:

Amount of CSR amount spent Details of entity/ Authority/ beneficiary of the registered owner (1) (2) (3) (4) (5) (6) CSR Registration Number, if applicable Name Registered address N/A 9.

Specify the reason(s), if the company has failed to spend two per cent of the average net
profit as per subsection (5) of section 135: N/A Date: 29.09.2025 Sd/- Rajesh Kohli {Chairman & Managing Director (Addl. Charge)} & (Chairperson, CSR Committee)



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.575
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 290

Preview:

be the Convener of the Committee Meetings. On the spirit of the law, Audit Committee was retained with available Directors as there was no Independent Directors during the FY 2024-25.

Annual Report 2024 - 25 In terms of section 177(8) of the Companies Act, 2013, the Board accepted all the recommendations made by the Audit Committee during the year. The terms of reference of Audit Committee are as enumerated under the provisions of the Companies Act, 2013, SEBI (Listing Obligations and Disclosure Requirements) Regulations, 2015 and the DPE guidelines on Corporate Governance which includes Oversight of the Company’s financial reporting process and the disclosure of its financial information t



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5624
Section     : Report on Corporate Governance
Type        : governance
Pages       : 23 - 39
Word Count  : 73

Preview:

of building a world class HMT. For and on behalf of the Board of Directors Sd/- (Rajesh Kohli) Place: Bengaluru Date: 29.09.2025 Chairman & Managing Director (Addl. Charge) DIN: 10333951

Annual Report 2024 - 25 Annexure - 1
ANNUAL REPORT ON CSR ACTIVITIES
1. Brief Outline on CSR Policy of the Company:

CSR Vision: To contribute the sustainable development and inclusive growth while taking care of People, Planet and organizational goals / growth.



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5518
Section     : Certificate on Corporate Governance
Type        : governance
Pages       : 40 - 46
Word Count  : 48

Preview:

to the MCA Circular dated September 22, 2025 read with MCA Circular dated May 5, 2020. The deemed venue for the AGM shall be the registered office of the Company.

For details, please refer to the Notice of this AGM No dividends have been declared. ii) Financial Calendar


========================================================================================================================
QUERY: What observations are mentioned in the secretarial audit report?
SECTION FILTERS: ['audit_report']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.59
Section     : Independent Auditor’s Report
Type        : audit_report
Pages       : 68 - 85
Word Count  : 280

Preview:

No.: 6941/2025 UDIN: UDIN F005521G001018071 Place: Bengaluru Date: 14th August, 2025 Note: This report is to be read with ‘Annexure - A’ which forms an integral part of this report.

Annual Report 2024 - 25 ‘Annexure - A’ To, The Members,
H.M.T (INTERNATIONAL) LIMITED
No.59, Bellary Road, Bangalore- 560032, Karnataka, India Our Report of even date is to be read along with this letter. 1. Maintenance of secretarial records is the responsibility of the Management of the Company. Our responsibility is to express an opinion on the secretarial records based on our audit. 2. We have followed the audit practices and processes as were appropriate to obtain reasonable assurance about the correctness



Rank #2
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5891
Section     : Independent Auditor’s Report
Type        : audit_report
Pages       : 68 - 85
Word Count  : 278

Preview:

(INTERNATIONAL) LIMITED (hereinafter called ‘the company’). Secretarial Audit was conducted in a manner that provided us a reasonable basis for evaluating the corporate conducts/statutory compliances and expressing our opinion thereon.

Based on our verification of the company’s books, papers, minute books, forms and returns filed and other records maintained by the company and also the information provided by the Company, its officers, agents and authorized representatives during the conduct of secretarial audit, we hereby report that in our opinion, the company has, during the audit period covering the financial year ended on 31st March 2025, (‘the audit period’) complied with the statutor



Rank #3
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5818
Section     : Secretarial Audit Report of HMT (International) Limited
Type        : audit_report
Pages       : 58 - 65
Word Count  : 283

Preview:

560032, (hereinafter called ‘the Company’). Secretarial Audit was conducted in a manner that provided to us a reasonable basis for evaluating the corporate conducts/statutory compliances and expressing our opinion thereon.

Based on our verification of the Company’s books, papers, minute books, forms and returns filed and other records maintained by the Company and also the information provided by the Company, its officers, agents and authorized representatives during the conduct of secretarial audit, we hereby report that in our opinion, the Company has, during the audit period covering the financial year ended on March 31, 2025 complied with the statutory provisions listed hereunder and al



Rank #4
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5593
Section     : Independent Auditor’s Report
Type        : audit_report
Pages       : 68 - 85
Word Count  : 114

Preview:

Annual Report 2024 - 25 Annexure-8
FORM NO. MR-3
SECRETARIAL AUDIT REPORT
FOR THE FINANCIAL YEAR ENDED 31st March, 2025 [Pursuant to section 204(1) of the Companies Act, 2013 and rule No.9 of the Companies (Appointment and Remuneration of Managerial Personnel) Rules, 2014 and Regulation 24A of SEBI(LODR) 2015] To, The Members,
H.M.T. (INTERNATIONAL) LIMITED
No.59, Bellary Road, Bengaluru -560032, Karnataka India We have conducted the secretarial audit of the compliance of applicable statutory provisions and the adherence to good corporate practices by H.M.T. (INTERNATIONAL) LIMITED (hereinafter called ‘the company’). Secretarial Audit was conducted in a manner that provided us a reasonable b



Rank #5
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5484
Section     : Secretarial Audit Report of HMT (International) Limited
Type        : audit_report
Pages       : 58 - 65
Word Count  : 262

Preview:

1617 / 2021 This Report is to be read along with my letter of even date which is annexed as Annexure A and Forms an integral part of this report.

Annual Report 2024 - 25 “Annexure A” To The Members
H.M.T. LIMITED
(CIN: L29230KA1953GOI000748)
HMT Bhavan, 59 Bellary Road, Bangalore 560032 My report of even date is to be read along with this letter. 1. Maintenance of secretarial records is the responsibility of the management of the Company. My responsibility is to express an opinion on these secretarial records based on my audit. 2. I have followed the audit practices and processes as were appropriate to obtain reasonable assurance about the correctness of the contents of the Secretarial reco


========================================================================================================================
QUERY: What does the CEO and CFO certificate mention?
SECTION FILTERS: ['compliance_certificate']
========================================================================================================================

Rank #1
------------------------------------------------------------------------------------------------------------------------
Score       : 0.5177
Section     : CEO & CFO Certificate
Type        : compliance_certificate
Pages       : 66 - 67
Word Count  : 59

Preview:

report is neither an assurance as to the future viability of the company nor of the efficacy or effectiveness with which the management has conducted the affairs of the company.


In [26]:
#Evaluate Hit@k and MRR

eval_questions = [
    {
        "question": "What are the main CSR activities carried out by the company?",
        "expected_section_type": "esg"
    },
    {
        "question": "Summarize the management discussion and analysis section.",
        "expected_section_type": "management_discussion"
    },
    {
        "question": "What does the report say about corporate governance?",
        "expected_section_type": "governance"
    },
    {
        "question": "What observations are mentioned in the secretarial audit report?",
        "expected_section_type": "audit_report"
    },
    {
        "question": "What does the CEO and CFO certificate mention?",
        "expected_section_type": "compliance_certificate"
    },
    {
        "question": "What are the major points in the directors report?",
        "expected_section_type": "board_report"
    },
    {
        "question": "What do the financial statements indicate about the company?",
        "expected_section_type": "financial_statements"
    },
    {
        "question": "What are the key performance highlights?",
        "expected_section_type": "highlights"
    }
]

eval_df = pd.DataFrame(eval_questions)
display(eval_df)

                                            question   expected_section_type
0  What are the main CSR activities carried out b...                     esg
1  Summarize the management discussion and analys...   management_discussion
2  What does the report say about corporate gover...              governance
3  What observations are mentioned in the secreta...            audit_report
4     What does the CEO and CFO certificate mention?  compliance_certificate
5  What are the major points in the directors rep...            board_report
6  What do the financial statements indicate abou...    financial_statements
7           What are the key performance highlights?              highlights

In [28]:
# ==========================================
# PHASE 3 — RETRIEVAL EVALUATION
# ==========================================

def evaluate_single_query(query: str, expected_section_type: str, top_k: int = 5):
    results = retrieve_top_k_chunks_filtered(query, top_k=top_k)

    matches = (results["section_type"] == expected_section_type).tolist()

    hit_at_k = int(any(matches))

    reciprocal_rank = 0.0
    for idx, is_match in enumerate(matches, start=1):
        if is_match:
            reciprocal_rank = 1.0 / idx
            break

    return {
        "question": query,
        "expected_section_type": expected_section_type,
        "top_k": top_k,
        "hit_at_k": hit_at_k,
        "mrr": reciprocal_rank,
        "top_section_types": results["section_type"].tolist(),
        "top_section_names": results["section_name"].tolist(),
        "top_scores": [round(x, 4) for x in results["retrieval_score"].tolist()]
    }


def evaluate_across_k(eval_df, k_values=[1, 3, 5, 10]):
    rows = []

    for k in k_values:
        temp_results = []

        for _, row in eval_df.iterrows():
            result = evaluate_single_query(
                query=row["question"],
                expected_section_type=row["expected_section_type"],
                top_k=k
            )
            temp_results.append(result)

        temp_df = pd.DataFrame(temp_results)

        rows.append({
            "k": k,
            "hit_rate": temp_df["hit_at_k"].mean(),
            "mrr": temp_df["mrr"].mean()
        })

    return pd.DataFrame(rows)

In [29]:
#Run

eval_results = []

for _, row in eval_df.iterrows():
    result = evaluate_single_query(
        query=row["question"],
        expected_section_type=row["expected_section_type"],
        top_k=5
    )
    eval_results.append(result)

eval_results_df = pd.DataFrame(eval_results)
display(eval_results_df)

,question,expected_section_type,top_k,hit_at_k,mrr,top_section_types,top_section_names,top_scores
0,What are the main CSR activities carried out b...,esg,5,1,1.0,"[esg, esg, esg, esg, esg]","[Annual Report on CSR Activities, Annual Repor...","[0.5222, 0.4335, 0.4288, 0.4077, 0.4047]"
1,Summarize the management discussion and analys...,management_discussion,5,1,1.0,"[management_discussion, management_discussion,...","[Management Discussions and Analysis, Manageme...","[0.4246, 0.4109, 0.3757, 0.3755, 0.3659]"
2,What does the report say about corporate gover...,governance,5,1,1.0,"[governance, governance, governance, governanc...","[Report on Corporate Governance, Report on Cor...","[0.642, 0.588, 0.575, 0.5624, 0.5518]"
3,What observations are mentioned in the secreta...,audit_report,5,1,1.0,"[audit_report, audit_report, audit_report, aud...","[Independent Auditor’s Report, Independent Aud...","[0.59, 0.5891, 0.5818, 0.5593, 0.5484]"
4,What does the CEO and CFO certificate mention?,compliance_certificate,5,1,1.0,"[compliance_certificate, compliance_certificat...","[CEO & CFO Certificate, CEO & CFO Certificate,...","[0.5177, 0.5158, 0.4465, 0.4304]"
5,What are the major points in the directors rep...,board_report,5,1,1.0,"[board_report, board_report, board_report, boa...","[Directors’ Report, Directors’ Report, Directo...","[0.5125, 0.5116, 0.4419, 0.3519, 0.317]"
6,What do the financial statements indicate abou...,financial_statements,5,1,1.0,"[financial_statements, financial_statements, f...","[Consolidated Financial Statement, Consolidate...","[0.6263, 0.6223, 0.6177, 0.6169, 0.6152]"
7,What are the key performance highlights?,highlights,5,0,0.0,"[board_report, financial_statements, esg, boar...","[Directors’ Report, Consolidated Financial Sta...","[0.2552, 0.2298, 0.2226, 0.2126, 0.2098]"

In [30]:
print("Hit@5 :", round(eval_results_df["hit_at_k"].mean(), 4))
print("MRR@5 :", round(eval_results_df["mrr"].mean(), 4))

Hit@5 : 0.875
MRR@5 : 0.875

In [31]:
#And then compare across k:

k_comparison_df = evaluate_across_k(eval_df, k_values=[1, 3, 5, 10])
display(k_comparison_df)

    k  hit_rate    mrr
0   1     0.875  0.875
1   3     0.875  0.875
2   5     0.875  0.875
3  10     0.875  0.875

In [ ]:
#Compare different k values

# def evaluate_across_k(eval_df, k_values=[1, 3, 5, 10]):
#     rows = []

#     for k in k_values:
#         temp_results = []
#         for _, row in eval_df.iterrows():
#             result = evaluate_single_query(
#                 query=row["question"],
#                 expected_section_type=row["expected_section_type"],
#                 top_k=k
#             )
#             temp_results.append(result)

#         temp_df = pd.DataFrame(temp_results)

#         rows.append({
#             "k": k,
#             "hit_rate": temp_df["hit_at_k"].mean(),
#             "mrr": temp_df["mrr"].mean()
#         })

#     return pd.DataFrame(rows)

# k_comparison_df = evaluate_across_k(eval_df, k_values=[1, 3, 5, 10])
# display(k_comparison_df)

In [ ]:
#Save evaluation outputs

phase3_eval_results_path = NOTEBOOK_RECORDS_DIR / "phase3_eval_results.csv"
phase3_k_comparison_path = NOTEBOOK_RECORDS_DIR / "phase3_k_comparison.csv"

eval_results_df.to_csv(phase3_eval_results_path, index=False, encoding="utf-8")
k_comparison_df.to_csv(phase3_k_comparison_path, index=False, encoding="utf-8")

print("Phase 3 evaluation outputs saved:")
print("-", phase3_eval_results_path)
print("-", phase3_k_comparison_path)

In [ ]:
#Optional answer generation preparation

def build_context_for_answer(query: str, top_k: int = 5, max_chars: int = 7000) -> str:
    results = retrieve_top_k_chunks_filtered(query, top_k=top_k)

    blocks = []
    total_chars = 0

    for idx, row in results.iterrows():
        block = f"""
[Chunk {idx + 1}]
Section Name: {row['section_name']}
Section Type: {row['section_type']}
Pages: {row['page_start']} - {row['page_end']}
Content:
{row['chunk_text']}
""".strip()

        if total_chars + len(block) > max_chars:
            break

        blocks.append(block)
        total_chars += len(block)

    return "\n\n".join(blocks)

In [ ]:
#Test

query = "What are the main CSR activities carried out by the company?"
context_text = build_context_for_answer(query, top_k=5)

print(context_text[:5000])

In [ ]:
#Prompt template for answer generation

def build_rag_prompt(query: str, top_k: int = 5) -> str:
    context = build_context_for_answer(query, top_k=top_k)

    prompt = f"""
You are a financial document assistant answering questions from an annual report.

Instructions:
- Answer only from the provided context.
- Do not make up facts.
- If the answer is not clearly available, say so.
- Prefer concise, factual answers.
- Mention section name and page range where relevant.

Question:
{query}

Retrieved Context:
{context}

Answer:
""".strip()

    return prompt

In [ ]:
#Prompt preview
print(build_rag_prompt("What are the main CSR activities carried out by the company?", top_k=5)[:6000])